

name: CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M%S')"
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Test with environment variables
       # run: echo  ${{ steps.date.outputs.date }}
        run: echo ${{ steps.extract_branch.outputs.branch }}
       
