

name: CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d-%h%s')"
      - name: Test with environment variables
        run: echo ${{ steps.date.outputs.date }}
